### ISSUE TITLE
conditional export?

### ISSUE THREAD

**Issue by uliw** [jkitchin/ox-ipynb#46] opened 2023-02-23 15:36 UTC
This harks back to and earlier question and based on https://github.com/jkitchin/scimax/issues/305 is likely not possible. Still, I recently started using notebooks in a class where it would be useful to have a version that the students get to see and version that the TA gets to see (i.e., with solutions and or comments wrt marking).

Drawers come to mind, but conditional drawer inclusion is not supported in the ox-ipynb.  I wonder, however whether the is another way (short of using, e.g., a python script) to exclude some content?

**Comment by jkitchin** [comment] 2023-02-23 17:01
Have you tried this: https://github.com/jkitchin/ox-ipynb/blob/master/ox-ipynb.el#L58?

**Comment by uliw** [comment] 2023-02-23 18:00
Just did. That is pretty nifty. The Begin Solution/End Solution allso works in the running text (which was my default scenario), but I don't see how to make this play nice with the org to pdf export. Anyway, I can print the notebook to PDF, so no problem.

Using `#+attr_ipynb: :remove t` on top of an ipython block resulted in an error though. 

thx!

**Comment by jkitchin** [comment] 2023-02-24 00:22
I think I pushed a fix above for the ipynb attr issue.

To get a pdf you can do this. maybe I should add an optional argument to those processors so you can use them directly, but this is pretty easy too.

#+BEGIN_SRC emacs-lisp
(let ((org-export-before-processing-hook '((lambda (_)
					     (cl-loop for func in '(ox-ipynb-remove-hidden
								     ox-ipynb-remove-solution
								     ox-ipynb-remove-remove)
								do (funcall func))))))
    (org-open-file (org-latex-export-to-pdf)))
#+END_SRC

**Comment by uliw** [comment] 2023-02-24 20:20
works like a charm. thx!

**Closed** 2023-02-24 20:23 UTC

**Comment by dinojr** [comment] 2024-09-05 21:34
> Have you tried this: https://github.com/jkitchin/ox-ipynb/blob/master/ox-ipynb.el#L58?

I'm missing something here. With the following, the code is still export with `(ox-ipynb-export-to-participant-notebook)`
```
#+begin_src ipython
 ### BEGIN SOLUTION 
liste1 = [ 2 * i for i in range(1,11) if 2*i >=4 and 2*i <=20]
print(liste1)
### END SOLUTION
#+end_src
```

**Comment by jkitchin** [comment] 2024-09-05 22:20
you have one extra space in front of `### BEGIN SOLUTION` that makes that happen I think.

**Comment by dinojr** [comment] 2024-09-05 22:48
Thanks for pointing this out. Actually the problem is worse since my orgmode setup indents all src blocks (especially those edited by `C-c '`). I have to manually delete all the extra spaces before the ### in the solution definition. Not very convenient. Changing the regexp to `"### BEGIN SOLUTION\\(.\\|\n\\)*?### END SOLUTION"` (without the `^`) in the definition of `ox-ipynb-remove-solution` seems to work for me.

I also tried 
```
#+attr_ipynb: :remove t
#+begin_src ipython
     liste1 = [ 2 * i for i in range(1,11) if 2*i >=4 and 2*i <=20]
     print(liste1)
#+end_src
```
but it throws an error

**Comment by jkitchin** [comment] 2024-09-05 23:45
That is a regression, I pushed a fix for remove. I also took out the ^ in those regexps. I am not sure why I thought they were important before, but I cant see an issue right now.
